### PR TITLE
Add js.ipfs.io to Transifex

### PR DESCRIPTION
**Pull request by lidel**
> (This is a part of Translation Project for IPFS GUIs, see https://github.com/ipfs/ipfs-gui/issues/50 for more details)

I've created https://www.transifex.com/ipfs/js-ipfs-website/  and set it up to automatically check for updates of https://github.com/ipfs/js.ipfs.io/raw/master/intl/messages/en.json  (not realtime, but twice a day), so if a new section is added to the website in the future, translation team will be notified about new strings on the same day changes land in `master`.

This PR:

- renames Chinese and Korean locales to solve issues noted in https://github.com/ipfs/ipfs-gui/issues/50#issuecomment-419430520
-  adds `.tx/config` which enables use of `tx` client for fetching new translations via `tx pull -a`

Relevant docs:

- [Installing the Transifex Client](https://docs.transifex.com/client/installing-the-client)
- [Understanding `.tx/config` file](https://docs.transifex.com/client/client-configuration#section-tx-config)
- Manual sync via Transifex Client 
  -  [Using Transifex with GitHub in Your Development Workflow](https://docs.transifex.com/integrations/github)
     - [Syncing a local project to Transifex with the Transifex Client](https://docs.transifex.com/integrations/github#section-using-the-client)

How to join translation team: https://www.transifex.com/ipfs/js-ipfs-website/
>  screenshot_26

### CODE REVIEW

**Comment by lidel** [comment]
Who is the maintainer of `js.ipfs.io`? 
Let me know your login on Transifex, I'll set permissions so you can upload new sources (`en`).

**Comment by lidel** [comment]
Added French ([screenshot](https://user-images.githubusercontent.com/157609/45646966-029d7f80-bac5-11e8-98d7-b393eeda76d0.png), initially started in https://github.com/ipfs/js.ipfs.io/pull/106)

**Comment by lidel** [comment]
Thanks! @PedroMiguelSS  fyi made you the Maintainer of https://www.transifex.com/ipfs/js-ipfs-website/ and a Coordinator of PT Language :)

**Comment by PedroMiguelSS** [comment]
Thank you for everything @lidel :pray:

**Pull request merged**
