### PR TITLE
chore: add languages

### LINKED ISSUE #187: Multiple translations vanished with the last release
image

### PR DESCRIPTION
**Pull request by PedroMiguelSS**
The copy of the whole website is complete now (at least I do think so 😛). 

The goal of this PR is to add multiple translations to the website.
It closes #187 as soon as we finish this task.

- [x] Portuguese - pt
- [x] Danish - da
- [x] French - fr
- [x] Italian - it
- [x] Korean - ko-KR
- [x] Polish - pl
- [ ] Chinese (China) - zh-CN
- [ ] Chinese (Hong-Kong) - zh-HK
- [x] Dutch - nl
- [ ] Swedish - sv
- [ ] German - de
- [ ] Norwegian - no

### CODE REVIEW

**Comment by PedroMiguelSS** [comment]
We must merge this PR asap so that we can deploy a new version of the website with all of these languages.
We need languages to be 100% translated to add them to the website. So, I would like to ask you to translate missing strings of your language on [transifex](https://www.transifex.com/ipfs/js-ipfs-website) and then I'll commit the new translations to this PR. 

Can you help me out, guys? 🙏

Danish - @jjoergensen
French - @sternhenri
Italian - @fazo96
Korean (ko-KR) - @Nipol
Polish - @lidel 
Chinese (China) - @junyaoren
Chinese (Hong-Kong) - @junyaoren
Dutch - @backkem
Swedish - @victorb 
German - @dignifiedquire 
Norwegian - ❓

@daviddias can you check please if I did tag the right people? I was checking translators on transifex but I don't know if their handle on transifex is the same on GitHub.

Furthermore, I noticed that @digitaldreamer is the coordinator of Norwegian. I saw that the name of the translator of this language is **Rjan**. But I did not find his handle (`OrjanR`) on GitHub.

**Comment by lidel** [comment]
@PedroMiguelSS added Polish and missing mappings for Chinese variants :+1: 

ps. fyi @digitaldreamer created initial IPFS Org at Transifex project two years ago and remains the coordinator of some languages until we find new maintainers :)

**Comment by backkem** [comment]
The Dutch translation is caught up again.

**Comment by jjoergensen** [comment]
Danish up-to-date as well!

**Comment by daviddias** [comment]
Very much pumped for this! Thank you all for helping us translate the js.ipfs.io Website! ❤️

**Comment by daviddias** [comment]
@PedroMiguelSS what's the ETA to ship the website with all of these translations?

**Comment by PedroMiguelSS** [comment]
I'll take just a few minutes to ship it once we have all of these translations completed @daviddias.

**Comment by satazor** [comment]
Perhaps we could release them as they are ready instead of waiting for all?

**Comment by fazo96** [comment]
I just updated the italian translation :+1:

**Comment by daviddias** [comment]
I'm with @satazor :) ship as they are ready.

**Comment by daviddias** [comment]
The website needs a button to say "Add your language" to point users to instructions on how to do so :)

You can put it as the last link after all the languages
image

**Comment by PedroMiguelSS** [comment]
> The website needs a button to say "Add your language" to point users to instructions on how to do so :)
> 
> You can put it as the last link after all the languages
> image

@daviddias should this button be written only in English? Or should it also be translated?
If so, since it's a very simple phrase, should I translate it on google translator?

**Comment by daviddias** [comment]
> since it's a very simple phrase, should I translate it on google translator?

Sounds like a great way to bootstrap it :)

**Comment by PedroMiguelSS** [comment]
This PR will be closed without all languages translated. But here is an issue to track the missing languages: [ipfs/js.ipfs.io/issues/218](https://github.com/ipfs/js.ipfs.io/issues/218).

**Pull request merged**
