### PR TITLE
feat: add ja-jp

### PR DESCRIPTION
**Pull request by dongri**
日本語追加しました

### CODE REVIEW

**Comment by lidel** [comment]
Thank you for contributing translation @dongri ! :+1: 

To avoid duplicated work, we don't accept direct PRs with locales.

Please submit those translations using Transifex project at https://www.transifex.com/ipfs/js-ipfs-website/ 
If you are not there yet, create an account and let me know your Transifex account name: I will add you to the ja-JP translation team so you can contribute there.

----

Why there is no need for submitting PRs via GitHub? Updating  them on Transifex is enough. We synchronize translations from Transifex before each release of new version of this website, so Transifex acts as a source of truth. An by using Transifex you will get informed about new things to translate that could be added in the future.

You can find more information at [README#translations](https://github.com/ipfs-shipyard/ipfs-webui#translations) and [ipfs/i18n](https://github.com/ipfs/i18n).

**Comment by dongri** [comment]
@lidel Thank you
Create Transifex account and sent request for join js.ipfs.io team

**Comment by dongri** [comment]
@lidel Please review 
https://www.transifex.com/ipfs/js-ipfs-website/translate/#ja_JP/messages-json/157359804

**Comment by lidel** [comment]
@dongri thank you for pinging me about it. Japanese should be added when #280 is merged.

**Pull request closed without merging**
