### PR TITLE
zh_CN Translated

### PR DESCRIPTION
**Pull request by alx696**
简体中文已经翻译完毕，可以启用了。

Please enable zh_CN.

### CODE REVIEW

**Comment by daviddias** [comment]
Hi @alx696 Thank you so much for helping us translate the page!

**Comment by lidel** [comment]
I  replied in https://github.com/ipfs-shipyard/ipfs-companion/pull/658 and  @alx696  is already on Transifex.  PRs like this should be closed without merging, as we want Transifex to be the source of truth for translations.

> To avoid duplicated work, we don't accept direct PRs: translations need to be submitted using Transifex project at https://www.transifex.com/ipfs/ipfs-companion/
(We synchronize translations with Transifex before each release.)
You can find more information at [..] [ipfs/i18n](https://github.com/ipfs/i18n)

**Comment by daviddias** [comment]
@lidel Ack!

Why isn't it online though

image

image

?

**Comment by daviddias** [comment]
js.ipfs.io is missing Chinese and Dutch

**Comment by daviddias** [comment]
thank you @PedroMiguelSS :)

**Pull request closed without merging**
