### PR TITLE
chore: upgrade to js-ipfs 0.35

### PR DESCRIPTION
**Pull request by alanshaw**
Static types and utils exports moved to package level in 0.35.

See https://blog.ipfs.io/80-js-ipfs-0-35/#api-changes

I will also update the CodePen examples.

Can anyone help with fixing up the tests - it looks like a babel issue.

### CODE REVIEW

**Comment by PedroMiguelSS** [comment]
I'll also update `service-worker-gateway` version as soon as [this issue](https://github.com/ipfs-shipyard/service-worker-gateway/issues/37) get solved. Then I'll merge this PR.

**Comment by PedroMiguelSS** [comment]
I've noticed I do not have permissions to merge/close PR and/or issues. 
@daviddias can you please fix this?

**Comment by olizilla** [comment]
@PedroMiguelSS I've added you as an admin to this repo!

**Comment by PedroMiguelSS** [comment]
Thank you @olizilla!

**Comment by PedroMiguelSS** [comment]
I will use this PR to update some other dependencies, namely:
- `service-worker-gateway` to v`0.1.13`
- `gatsby` to v`2.3.33`
- `cypress` to v`3.2.0`
- `gatsby-plugin-webpack-bundle-analyzer` to v`1.0.4`

**Pull request merged**
