### PR TITLE
feat: add tooltip for browsers with no serviceworkers

### PR DESCRIPTION
**Pull request by vasco-santos**
Added a tooltip message and disable the service worker toggle button when the service worker is not compatible with the browser.

Minor refactor on unregister as well.

### CODE REVIEW

**Comment by diasdavid** [comment]
Did you test this in Safari, @vasco-santos? It is not working for me nor it shows any message.

**Comment by vasco-santos** [comment]
will check it now!

**Comment by vasco-santos** [comment]
@diasdavid `JS` is not working in `Safari` right now 😢 
Will look into it

**Comment by fsdiogo** [comment]
I'm merging this because I need it for another PR and the fact that it's not working in Safari isn't due to this PR.

**Comment by vasco-santos** [comment]
Safari fixed [here](https://github.com/ipfs/js.ipfs.io/pull/64)

**Pull request merged**
