### PR TITLE
feat: add chinese and update korean

### PR DESCRIPTION
**Pull request by PedroMiguelSS**
This PR adds Chinese language and updates Korean language.

### CODE REVIEW

**Comment by daviddias** [comment]
@PedroMiguelSS can you make a new release of the website?

**Comment by PedroMiguelSS** [comment]
On it!

**Comment by PedroMiguelSS** [comment]
Let's just wait for the CI to get green :)

**Comment by daviddias** [comment]
#protip if CI takes more than 10 mins, just restart it -- learning from https://github.com/ipfs/infra/issues/474

**Comment by daviddias** [comment]
Tracking it here https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs.ipfs.io/detail/master/72/pipeline

**Comment by PedroMiguelSS** [comment]
Before deploying it we need to add the website to IPFS and update the resulting hash in each translation file. Thus, master will be updated soon and hence, the CI will run again.

**Comment by daviddias** [comment]
@PedroMiguelSS that should just be loaded on the browsers using DNS resolve so that we are always pointing to the latest of each page. Adding this as an issue for after

**Pull request merged**
