### PR TITLE
perf: use svg sprites & urls instead of all inline

### PR DESCRIPTION
**Pull request by satazor**
- Moved images to folders closest to components, allowing for future optimizations with sprites
- Renamed some files, variables and data
- Fixed footer element placements
- Fixed code consistency with spaces in some files
- Removed locale utils, it's not necessary at alls
- Removed unused data files
- Improved css modules hash in production
- Improved videos sections hover animations
- Fixed play icon being loaded from imgur instead of IPFS
- Used standard transitions whenever possible

Refs #69

### CODE REVIEW

**Comment by satazor** [comment]
I wanted to make separate PRs for everything but I had no time. Additionally, I will follow up more improvements after DWeb.

**Comment by diasdavid** [comment]
@satazor merge conflicts

**Comment by diasdavid** [comment]
image

**Comment by diasdavid** [comment]
@satazor do you feel confident that this can be achieved this morning?

**Comment by diasdavid** [comment]
@PedroMiguelSS can you handle the merge conflicts of this one? Hoping to see this published today.

**Comment by satazor** [comment]
I've rebased again. Here's a screenshot of the before and after:

screen shot 2018-08-09 at 02 04 24

There's still more minor improvements to do. We need to do that as part of #69

**Comment by satazor** [comment]
@PedroMiguelSS can we please merge this asap to avoid more conflicts? Please review the PR carefully as there is a lot of changes. I'm sorry to not split it into more MRs but I really didn't have the time.

**Pull request merged**
